In [1]:
import pprint 
import scipy
import scipy.linalg as sl
A =scipy.array([[2,-1,-2],[-4,6,3],[-4,-2,8]])
P,L,U = sl.lu(A)
print ("A the given matrix:")
pprint.pprint(A)

print (" matrix with pivoted elements :")
pprint.pprint(P)

print("lower triangular matrix")
pprint.pprint(L)

print("Upper traingular:")
pprint.pprint(U)

A the given matrix:
array([[ 2, -1, -2],
       [-4,  6,  3],
       [-4, -2,  8]])
 matrix with pivoted elements :
array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])
lower triangular matrix
array([[ 1.  ,  0.  ,  0.  ],
       [ 1.  ,  1.  ,  0.  ],
       [-0.5 , -0.25,  1.  ]])
Upper traingular:
array([[-4.  ,  6.  ,  3.  ],
       [ 0.  , -8.  ,  5.  ],
       [ 0.  ,  0.  ,  0.75]])


<ipython-input-1-7e3f8dbedd7c>:4: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  A =scipy.array([[2,-1,-2],[-4,6,3],[-4,-2,8]])


In [2]:
L@U


array([[-4.,  6.,  3.],
       [-4., -2.,  8.],
       [ 2., -1., -2.]])